/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ErpSearchForm: typeof import('./src/components/ErpSearchForm.vue')['default']
    ErpTable: typeof import('./src/components/ErpTable/ErpTable.vue')['default']
    LayAvatar: typeof import('@layui/layui-vue')['LayAvatar']
    LayBody: typeof import('@layui/layui-vue')['LayBody']
    LayBreadcrumb: typeof import('@layui/layui-vue')['LayBreadcrumb']
    LayBreadcrumbItem: typeof import('@layui/layui-vue')['LayBreadcrumbItem']
    LayButton: typeof import('@layui/layui-vue')['LayButton']
    LayCard: typeof import('@layui/layui-vue')['LayCard']
    LayCol: typeof import('@layui/layui-vue')['LayCol']
    LayDropdown: typeof import('@layui/layui-vue')['LayDropdown']
    LayDropdownMenu: typeof import('@layui/layui-vue')['LayDropdownMenu']
    LayDropdownMenuItem: typeof import('@layui/layui-vue')['LayDropdownMenuItem']
    LayForm: typeof import('@layui/layui-vue')['LayForm']
    LayFormItem: typeof import('@layui/layui-vue')['LayFormItem']
    LayHeader: typeof import('@layui/layui-vue')['LayHeader']
    LayInput: typeof import('@layui/layui-vue')['LayInput']
    LayLayer: typeof import('@layui/layer-vue')['LayLayer']
    LayLayout: typeof import('@layui/layui-vue')['LayLayout']
    LayMenu: typeof import('@layui/layui-vue')['LayMenu']
    LayMenuItem: typeof import('@layui/layui-vue')['LayMenuItem']
    LayRow: typeof import('@layui/layui-vue')['LayRow']
    LaySubMenu: typeof import('@layui/layui-vue')['LaySubMenu']
    LayTab: typeof import('@layui/layui-vue')['LayTab']
    LayTabItem: typeof import('@layui/layui-vue')['LayTabItem']
    LayTable: typeof import('@layui/layui-vue')['LayTable']
    LayTag: typeof import('@layui/layui-vue')['LayTag']
    LayTooltip: typeof import('@layui/layui-vue')['LayTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
